#.travis.yml

dist: trusty
sudo: false # ensures we use the container stack (it's faster)

cache:
  directories:
    - node_modules

language: node_js

addons:
  artifacts:
    s3_region: ap-southeast-2
    paths:
      - prod.tar.gz
      - stag.tar.gz
  apt:
    packages:
      - google-chrome-stable

node_js:
  - "8.1.3"

env:
  - TEST_SUITE=build
  - TEST_SUITE=unit
  - TEST_SUITE=e2e

before_script:
  - if [ "$TEST_SUITE" == "e2e" ]; then export DISPLAY=:99.0; fi
  - if [ "$TEST_SUITE" == "e2e" ]; then eval "sh -e /etc/init.d/xvfb start &"; fi
  - if [ "$TEST_SUITE" == "e2e" ]; then sleep 3; fi # let xvfb start up
  - if [ "$TEST_SUITE" == "e2e" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ "$TRAVIS_BRANCH" == "master" ]; then npm install -g firebase-tools; fi
  - npm install -g @angular/cli@1.3.1

script:
  - if [ "$TEST_SUITE" == "unit" ]; then karma start; fi
  - if [ "$TEST_SUITE" == "e2e" ]; then ng e2e --environment=staging --target=production --aot; fi
  - if [ "$TEST_SUITE" == "e2e" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then sh deploy/staging.sh; fi
  - if [ "$TEST_SUITE" == "e2e" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then sh deploy/prod.sh; fi
  - if [ "$TEST_SUITE" == "build" ]; then sh deploy/build.sh; fi
